name: CI Testing
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: "Python ${{ matrix.python }} Django ${{ matrix.django }}"
    runs-on: ubuntu-24.04
    strategy:
      # max-parallel: 8  # default is max available
      fail-fast: false
      matrix:
        include:
          # Django 2.2
          - django: "2.2"
            python: "3.8"
          # Django 3.2
          - django: "3.2"
            python: "3.8"
          # Django 4.2
          - django: "4.2"
            python: "3.8"
          # Django 5.1
          - django: "5.1"
            python: "3.10"
          # Django 5.2
          - django: "5.2"
            python: "3.12"

    steps:
      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Packages
        run: |
          python -m pip install -U pip
          python -m pip install "Django~=${{ matrix.django }}" django-storages boto3 codecov -e .[tests]

      - name: Run Tests
        run: |
          echo "Python ${{ matrix.python }} / Django ${{ matrix.django }}"
          coverage run --rcfile=.coveragerc runtests.py
          codecov
        continue-on-error: ${{ contains(matrix.django, '4.0') }}
